### ISSUE TITLE
Sunday Scrolling - does not work

### ISSUE THREAD

**Issue by Jdrucke01** [rahultadak/MMM-CalvinAndHobbes#2]
Just installed the module this week. Love it. Unfortunately, the scrolling for Sunday does not work. Any ideas on what to to correct?

**Comment by dathbe** [comment]
This is the error message I get when it tries to scroll:

```
MMM-CalvinAndHobbes.js:98 Scrolling now
MMM-CalvinAndHobbes.js:101  Uncaught TypeError: Cannot read properties of null (reading 'naturalHeight')
    at Class.scrollComic (MMM-CalvinAndHobbes.js:101:33)
    at MMM-CalvinAndHobbes.js:41:22
scrollComic @ MMM-CalvinAndHobbes.js:101
(anonymous) @ MMM-CalvinAndHobbes.js:41
setInterval
start @ MMM-CalvinAndHobbes.js:40
startModules @ loader.js:29
loadNextModule @ loader.js:239
await in loadNextModule
loadNextModule @ loader.js:232
await in loadNextModule
loadNextModule @ loader.js:232
await in loadNextModule
loadModules @ loader.js:242
await in loadModules
init @ main.js:588
await in init
(anonymous) @ main.js:737
```
